// Generated by CIRCT firtool-1.48.0
module VCA(
  input         clock,
                reset,
                io_en,
  input  [15:0] io_in,
                io_control,
  output [15:0] io_out
);

  assign io_out = io_en ? io_in * io_control : 16'h0;
endmodule

